package io.pivotal.gemfire.toolsmiths.hydradb.data.hydra;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.springframework.data.domain.Persistable;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
@Entity
@Table( name = "HYDRA_TEST" )
public class HydraTest implements Persistable<Integer>
{

	private static final long serialVersionUID = 1L;

	@Id
	private Integer id;

	private String conf;

	private String fullTestSpec;

	private Integer hydraTestsuiteId;

	private transient boolean persisted;

	private HydraTestsuite hydraTestsuite;

	public HydraTest ()
	{

	}

	public Integer getId ()
	{
		return this.id;
	}

	public boolean isNew ()
	{
		return this.id == null;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public void setConf (String conf)
	{
		this.conf = conf;
	}

	public String getConf ()
	{
		return this.conf;
	}

	public void setFullTestSpec (String fullTestSpec)
	{
		this.fullTestSpec = fullTestSpec;
	}

	public String getFullTestSpec ()
	{
		return this.fullTestSpec;
	}

	public void setHydraTestsuiteId (Integer hydraTestsuiteId)
	{
		this.hydraTestsuiteId = hydraTestsuiteId;
	}

	public Integer getHydraTestsuiteId ()
	{
		return this.hydraTestsuiteId;
	}

	public void setPersisted (Boolean persisted)
	{
		this.persisted = persisted;
	}

	public Boolean getPersisted ()
	{
		return this.persisted;
	}

	public void setHydraTestsuite (HydraTestsuite hydraTestsuite)
	{
		this.hydraTestsuite = hydraTestsuite;
	}

	public HydraTestsuite getHydraTestsuite ()
	{
		return this.hydraTestsuite;
	}

	@Override
	public String toString () 
	{
		return ToStringBuilder.reflectionToString (this); 
	}

	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}