package io.pivotal.gemfire.toolsmiths.hydradb.data.hydra;

import org.springframework.data.domain.Persistable;
import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
public class HydraTestDetailExt implements Persistable<Long>
{

	private static final long serialVersionUID = 1L;

	private Long id;

	private String logLocation;

	private transient boolean persisted;

	private HydraTestDetail hydraTestsuiteDetail;

	public HydraTestDetailExt ()
	{

	}

	public Long getId ()
	{
		return this.id;
	}

	public boolean isNew ()
	{
		return this.id == null;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public void setLogLocation (String logLocation)
	{
		this.logLocation = logLocation;
	}

	public String getLogLocation ()
	{
		return this.logLocation;
	}

	public void setPersisted (Boolean persisted)
	{
		this.persisted = persisted;
	}

	public Boolean getPersisted ()
	{
		return this.persisted;
	}

	public void set (HydraTestDetail hydraTestsuiteDetail)
	{
		this.hydraTestsuiteDetail = hydraTestsuiteDetail;
	}

	public HydraTestDetail get ()
	{
		return this.hydraTestsuiteDetail;
	}

	@Override
	public String toString () 
	{
		return ToStringBuilder.reflectionToString (this); 
	}

	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}