package io.pivotal.gemfire.toolsmiths.hydradb.data.hydra;

import org.springframework.data.domain.Persistable;
import org.apache.commons.lang3.builder.ToStringBuilder;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
@Entity
@Table( name = "HYDRA_TESTSUITE" )
public class HydraTestsuite implements Persistable<Integer>
{

	private static final long serialVersionUID = 1L;

	@Id
	private Integer id;

	private String name;

	private transient boolean persisted;


	public HydraTestsuite ()
	{

	}

	public Integer getId ()
	{
		return this.id;
	}

	public boolean isNew ()
	{
		return this.id == null;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public void setName (String name)
	{
		this.name = name;
	}

	public String getName ()
	{
		return this.name;
	}

	public void setPersisted (Boolean persisted)
	{
		this.persisted = persisted;
	}

	public Boolean getPersisted ()
	{
		return this.persisted;
	}

	@Override
	public String toString () 
	{
		return ToStringBuilder.reflectionToString (this); 
	}

	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}